import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import welcome from '../public/Welcome.png'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Image
          alt='Welcome screen illustration'
          src={welcome}
          placeholder='blur'
          layout='intrinsic' />
        <h2>Never miss an update...</h2>
        <p>Stay connected and share limitlessly</p>
      </div>
    </Container>
  )
}

const Container = styled.div`
  display: grid;
  place-items: center;
  background-color: #f8fafc;
  width: 100%;
  height: 100%;
  text-align: center;
`